### ISSUE TITLE
Error d8a0a028 on downloading some files.

### ISSUE THREAD

**Issue by Hikari-chan** [LiquidFenrir/MultiUpdater#11]
Sometimes, on certain files, MultiUpdater will fail to download and return the error code d8a0a028. For me, this occurs at odd intervals only: the first try it'll fail and return d8a0a028, the second time it'll work, fail the third, succeed the fourth, etc. This has been a long-standing issue, and has managed to persist even after overhauling the way MultiUpdater handles downloading files. This is a basic description of the error:

`Module: HTTP (40) | Description: 40 | Summary: Invalid state (5) | Level: Permanent (27)`

Here's a list of some common payload update URLs to emphasize the strangeness of this error:

- https://astronautlevel2.github.io/Luma3DS/release.zip - **Not affected**
- https://astronautlevel2.github.io/Luma3DS/release.zip - **Not affected**
- http://d0k3.secretalgorithm.com/latest/Decrypt9WIP - **Not affected**
- http://d0k3.secretalgorithm.com/latest/EmuNAND9 -  **Affected**
- http://d0k3.secretalgorithm.com/latest/GodMode9 - **Affected**

As we can see, files of the exact same type, similar size, similar path, similar URL length, and on the exact same server are not consistently affected by this error. This strikes me as extremely strange; any help with this would be appreciated, as I'm not sure what's going wrong, or why.

**Comment by NinjaBoyLao** [comment]
I can confirm that hourglass9 will not work the first try but work fine the 2nd, and that godmode9 and emunand9 also do that

**Comment by Hikari-chan** [comment]
After much testing, I was unable to reproduce this elsewhere, leading me to think it's either an issue with SecretAlgorithm, or an issue with how ctrulib's httpc handles redirects and relative URLs. I'll be updating the config.json shortly to resolve this issue with SA.
