### ISSUE TITLE
GitHub API Support

### ISSUE THREAD

**Issue by igromanru** [LiquidFenrir/MultiUpdater#15]
Could you please add support for GitHub API so it can be configuration to download a special file from latest GitHub release?
For example:
Here is your repo https://api.github.com/repos/LiquidFenrir/MultiUpdater/releases/latest , under "assets" there are the *browser_download_url* tag with the download link to your latest release (MultiUpdater1.6.zip).
EDIT: If I will got enough time, I will try to implement it myself. https://github.com/igromanru/MultiUpdater-VS

**Comment by LiquidFenrir** [comment]
Covered in commit e3462b3. Might need sanitizing/error reporting
