### ISSUE TITLE
fail to download or install some .cia

### ISSUE THREAD

**Issue by Tobyheiam** [LiquidFenrir/MultiUpdater#19]
![screen shot 2017-06-10 at 2 55 05 pm](https://user-images.githubusercontent.com/22422919/27005446-d15d0102-4dec-11e7-8352-21b97f576f68.png)

**Comment by LiquidFenrir** [comment]
Thats because I havent made a release with the github api stuff yet, am not home so cant take care of that now. Besides, there are bugs to fix in it
