### ISSUE TITLE
httpcGetDownloadSizeState isn't safe to use

### ISSUE THREAD

**Issue by ksanislo** [LiquidFenrir/MultiUpdater#2]
This call will return a size of 0 even if there's data, in the case of Transfer-Encoding: chunked, or other CGI type responses... Look at the patch I [submitted to lpp-3ds](https://github.com/Rinnegatamante/lpp-3ds/commit/26b96a2f414b764b742c152b341dbe5a5bb3b700) for a similar issue and how it avoid it by looping over httpcDownloadData() until finished instead.

**Comment by LiquidFenrir** [comment]
Thanks! I restarted working on the project, and this will be added soon!

**Comment by ksanislo** [comment]
Cool, just fwiw the 3ds-example for http has been updated to be a better example if you want a clean reference.

**Comment by LiquidFenrir** [comment]
Thanks for telling me that, I'll take a look at it.

**Comment by Hikari-chan** [comment]
I fixed this in a new branch, httpc_overhaul. It should be merged to master soon, after a bit more testing.
