### ISSUE TITLE
ARM11 System crash.

### ISSUE THREAD

**Issue by JourneyOver** [LiquidFenrir/MultiUpdater#20]
Seem to be getting a crash whenever I attempt to grab from this. It's not just a MultiUpload crash but a full system crash (arm11) to the point it creates a crash dump and shuts down my system.

      "name":"SOS: Trio NTR Cheats",
      "url":"https://github.com/KunoichiZ/3OT-NTR-Plugin",
      "inrelease":"plugin.zip",
      "inzip":"000400000019F500/Story_of_Seasons_Trio_of_Towns.plg",
      "path":"/plugin/000400000019F500/Story_of_Seasons_Trio_of_Towns.plg"

but doing downloading this 

      "name":"Themely (latest release)",
      "url":"https://github.com/ErmanSayin/Themely",
      "inrelease":"Themely.cia",
      "path":"/Homebr3w/CIAs/Themely.cia"

doesn't seem to produce a crash

link to the dump -- http://www.mediafire.com/view/vohizjl1g2lnb5x

this is my whole [config.json](https://gist.github.com/JourneyOver/70f5b63a4d23849bb591e6464ac20672)

**Comment by LiquidFenrir** [comment]
the crash happens at https://github.com/LiquidFenrir/MultiUpdater/blob/master/source/gitapi.c#L38
that's all I know for now, will look into it.
further: it happens in jansson, at https://github.com/akheron/jansson/blob/2.10/src/value.c#L764

**Comment by JourneyOver** [comment]
Sounds good hopefully you can find the cause as to why it's crashing there as it is pretty much a 100% crash every time.

**Comment by JourneyOver** [comment]
Just tested the latest release, no crashes now :D though I do still get annoyed by the random error due to a folder not existing before hand when downloading a file so having to go into ftp just to make a damn folder lol >.>

**Comment by LiquidFenrir** [comment]
you can also use CTRXplorer for that, or FBI, or GodMode9. fairly easy :)

**Comment by JourneyOver** [comment]
Ah yea forgot they can make folders >..< just would be easier and nicer if MU did it as well lmao since sometimes I delete a folder/file on my SD card and then in the future go and redownload it and then it's like a woops gotta make the folder again xD
