### ISSUE TITLE
Have a question about the latest release on github

### ISSUE THREAD

**Issue by JKC-A9LH** [LiquidFenrir/MultiUpdater#21]
Hello @LiquidFenrir , l have a question about the latest release on github. For example, l want to update Luma3DS(the latest release on github), however, the zip's name is not the same such as Luma3DSv8.0.7z and Luma3DSv7.1.7z. So how could l write the config.json? The same as LumaLocaleSwitch and D9 G9 H9(lateset releases on github) and if l need two things in the zip or 7z, how could l write the code.

**Comment by LiquidFenrir** [comment]
Unfortunately, you cannot at the moment as it does a dumb string match. I'm planning to add pattern matching (maybe wildcard or regex) in the future, but for now it's impossible.

**Comment by JKC-A9LH** [comment]
Thank you for your efforts~! @LiquidFenrir
