### ISSUE TITLE
Error codes are displayed as hex, rather than signed int

### ISSUE THREAD

**Issue by ValShaped** [LiquidFenrir/MultiUpdater#24]
While trying to update the 3DSX version of Hamcha and KunoichiZ's LumaUpdater, I ran into an issue with zip file decompression which gave the output

`Opening as a zip file...`
`Operation failed!`
`Error: 0xfffffff8`

Looking in [file.h](https://github.com/LiquidFenrir/MultiUpdater/blob/master/source/file.h), that looks like it could be error -8 (`0xfffffff8`). It's a tiny bit confusing trying to debug when all the error codes are displayed in 2's compliment.

I've since fixed the issue with my config (invalid "inarchive")

**Comment by LiquidFenrir** [comment]
not a problem, it's hex because of the normal Result (from 3ds/ctrulib function)
could change normal numbers from negative to positive to make them easier to read
