### ISSUE TITLE
Gives error code -8 if there isn't a space between the tag and data in "inarchive"

### ISSUE THREAD

**Issue by ValShaped** [LiquidFenrir/MultiUpdater#26]
In the config, if MultiUpdater is given an input like this:

		{
			"name":"Multiupdater",
			"url":"https://github.com/LiquidFenrir/MultiUpdater",
			"inrelease":"MultiUpdater-*zip",
			"inarchive":"3ds/MultiUpdater/MultiUpdater.3dsx",
			"path":"/3ds/MultiUpdater/MultiUpdater.3dsx"
		}

MultiUpdater will refuse to extract it (error -8). However, when given an input like this:

		{
			"name": "Multiupdater",
			"url": "https://github.com/LiquidFenrir/MultiUpdater",
			"inrelease": "MultiUpdater-*zip",
			"inarchive": "3ds/MultiUpdater/MultiUpdater.3dsx",
			"path": "/3ds/MultiUpdater/MultiUpdater.3dsx"
		}

Multiupdater will work as intended. It doesn't say that it's malformed JSON, is this a bug?

**Comment by ValShaped** [comment]
It will also work with any combination of  spaces or lack thereof for "name", "url", "inrelease", and "path". As far as I can see, it only fails to update the file if "inarchive": doesn't have a space afterwards.

**Comment by LiquidFenrir** [comment]
just tried it, couldn't reproduce. try latest release?

**Comment by ValShaped** [comment]
Alright

**Comment by ValShaped** [comment]
I tried it again on latest, I think it's fixed.
