### ISSUE TITLE
Pattern matching in "inarchive"

### ISSUE THREAD

**Issue by ValShaped** [LiquidFenrir/MultiUpdater#27]
The mGBA emulator's folder layout changes based on the build date and release number.

As such, the ability to do this:

		{
			"name": "mGBA",
			"url": "https://github.com/mgba-emu/mgba",
			"inrelease": "mgba-*-3ds.7z",
			"inarchive": "mGBA-*-*-*-*-3ds/mgba.3dsx",
			"path": "/3ds/ftpd/ftpd.3dsx"
		}

Would be amazing. (if this is already implemented, feel free to close.)

**Comment by LiquidFenrir** [comment]
little note: the check is case-sensitive so the "mgba" in the "inrelease" would have to be "mGBA" too

**Comment by ValShaped** [comment]
It's "mgba" (all lowercase) but thanks!

**Comment by LiquidFenrir** [comment]
not the repo name, the release file name.
https://vgy.me/QtPagZ.png
