### ISSUE TITLE
Issue I ran into 40 seconds ago

### ISSUE THREAD

**Issue by 46620** [LiquidFenrir/MultiUpdater#28]
When there is about 3 or less items on screen, it gives me the error:
There is an error in your config.json.
If you want ill add the code
EDIT: Code below

{
	"entries": [
		{
			"name": "Payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "Luma3DS (latest release)",
			"url": "https://github.com/AuroraWright/Luma3DS",
			"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/boot.firm"
		},
		{
			"name": "Luma3DS (latest commit)",
			"url": "https://astronautlevel2.github.io/Luma3DS/latest.zip",
			"inarchive": "out/boot.firm",
			"path": "/boot.firm"
		}
	]
}

**Comment by LiquidFenrir** [comment]
Try with that one and tell me if it persists
[MultiUpdater.zip](https://github.com/LiquidFenrir/MultiUpdater/files/1100886/MultiUpdater.zip)

**Comment by ValShaped** [comment]
I noticed that you still have an "inzip" tag in the "Payloads" one. 

"inarchive" covers both cases.

**Comment by 46620** [comment]
@LiquidFenrir there isnt any issue with that config. I added a few blank slots on the one with 3 and it started to work.

_Sent from my LGE LG-K371 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LiquidFenrir** [comment]
Just tried it here, works fine with only 3 entries, or even less. Make sure you indent it properly, with tabs, and add a newline at the end. Like so:
```
{
	"entries": [
		{
			"name": "Payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "Luma3DS (latest release)",
			"url": "https://github.com/AuroraWright/Luma3DS",
			"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/boot.firm"
		},
		{
			"name": "Luma3DS (latest commit)",
			"url": "https://astronautlevel2.github.io/Luma3DS/latest.zip",
			"inarchive": "out/boot.firm",
			"path": "/boot.firm"
		}
	]
}
```
