### ISSUE TITLE
Delete the zip files it downloads after extracting and copying the needed file

### ISSUE THREAD

**Issue by droped** [LiquidFenrir/MultiUpdater#3]

**Comment by LiquidFenrir** [comment]
I restarted working on the project, and this will be added soon!
This is what the "remove(zip_path);" on line 84 of file.c is for, but apparently it doesn't work on 3ds. I'll have to find another way.

**Comment by JourneyOver** [comment]
Getting close to getting this fixed up any? :o still doesn't delete zip files it downloads at all after extracting and such :/
