### ISSUE TITLE
CTRNAND bug?

### ISSUE THREAD

**Issue by mariogamer2** [LiquidFenrir/MultiUpdater#31]
after updating luma to latest release on ctrnand (just to test since it was already at latest release), the file in ctrnand:/boot.firm is super weird and isn't the same as before (and it's not at all a FIRM file)

Copying sd:/boot.firm fix the issue

**Comment by LiquidFenrir** [comment]
Thanks, that was not related to ctrnand but to 7z extraction. Fixed now!
