### ISSUE TITLE
failed file extraction

### ISSUE THREAD

**Issue by zweilous** [LiquidFenrir/MultiUpdater#33]
> Couldn't read data from the file in the archive
> Extraction failed!
> Error: 0xfffffff8

```
		{
			"name": "CTRXplorer.3dsx (latest commit)",
			"url": "https://d0k3.secretalgorithm.com/CTRXplorer/latest.zip",
			"inarchive": "3ds-arm/3ds/CTRXplorer/CTRXplorer.3dsx",
			"path": "/3ds/CTRXplorer/CTRXplorer.3dsx"
		}
```

**Comment by ValShaped** [comment]
I'm having the same issue with 

		{
			"name": "LumaUpdater",
			"url": "https://github.com/KunoichiZ/lumaupdate",
			"inrelease": "lumaupdater-*zip",
			"inarchive": "3ds/lumaupdater/lumaupdater.3dsx",
			"path": "/3ds/lumaupdater/lumaupdater.3dsx"
		}

**Comment by LiquidFenrir** [comment]
[MultiUpdater-v3.2.1-1-g6cee413.zip](https://github.com/LiquidFenrir/MultiUpdater/files/1116847/MultiUpdater-v3.2.1-1-g6cee413.zip)
Try this and tell me if it fixed it for you as well

**Comment by ValShaped** [comment]
Extraction successful!

**Comment by LiquidFenrir** [comment]
Good, thanks!

**Comment by ValShaped** [comment]
Was it because sometimes unzReadCurrentFile would return 0?

**Comment by LiquidFenrir** [comment]
yeah, when it reaches eof.
https://github.com/LiquidFenrir/MultiUpdater/blob/master/source/minizip/unzip.h#L193-L200

**Comment by ValShaped** [comment]
Ah, makes sense.
