### ISSUE TITLE
Download Failed!

### ISSUE THREAD

**Issue by JourneyOver** [LiquidFenrir/MultiUpdater#34]
For some reason on these I am getting "download failed!" errors

Full error is 
```
Error: Http status code is not 200 OK.
Status code: 404
download failed!
Error: 0xffffffff
```

These are what I am trying to download 

```
    {
      "name":"PKM SM NTR Cheats (Moon)",
      "url":"https://github.com/AnalogMan151/sumoCheatMenu",
      "inrelease":"SUMO-old3DS.zip",
      "inarchive":"0004000000175E00/Moon.plg",
      "path":"/plugin/0004000000175E00/PKM_Moon.plg"
    },
    {
      "name":"PKM SM NTR Cheats (Sun)",
      "url":"https://github.com/AnalogMan151/sumoCheatMenu",
      "inrelease":"SUMO-old3DS.zip",
      "inarchive":"0004000000164800/Sun.plg",
      "path":"/plugin/0004000000164800/PKM_Sun.plg"
    }
```
Either one of them ends up throwing the error. also trying 

```
    {
      "name":"Ever Oasis NTR Cheats",
      "url":"https://github.com/Slattz/Ever_Oasis-NTR-Cheat",
      "inrelease":"E-Oasis-NTR-Cheats-v*zip",
      "inarchive":"plugin/00040000001A4800/E-Oasis_USA.plg",
      "path":"/plugin/00040000001A4800/Ever_Oasis.plg"
    }
```
seems to end up throwing the same error..

**Comment by RubberBrony** [comment]
Try putting a space between the "tag": "and the data"

It might do nothing, but try:

`    {
        "name":"PKM SM NTR Cheats (Sun)",
        "url":"https://github.com/AnalogMan151/sumoCheatMenu",
        "inrelease":"SUMO-old3DS.zip",
        "inarchive":"0004000000164800/Sun.plg",
        "path":"/plugin/0004000000164800/PKM_Sun.plg"
    }`

**Comment by LiquidFenrir** [comment]
Just tried it, the pokemon sun/moon plugins downloaded and extracted properly, but the Ever Oasis one didn't.
It's because there's a typo in the url, it needs a `s` at the end, like so:
``https://github.com/Slattz/Ever_Oasis-NTR-Cheats``

**Comment by JourneyOver** [comment]
Wonder why they are working now, when earlier they wasn't working at all .-. guess the github api was just being wonky or something then for just those two..

Wonder how I missed the "s" for cheats when all I did was a copy paste of the url >..< but oh well. The inrelease looks right in the above code for things release like "E-Oasis-NTR-Cheats-v1.1.zip" right?

**Comment by LiquidFenrir** [comment]
yep, it works fine after the url is fixed

**Comment by JourneyOver** [comment]
alright great, thanks :)
