### ISSUE TITLE
Another bug I ran into

### ISSUE THREAD

**Issue by 46620** [LiquidFenrir/MultiUpdater#36]
So this time I'll put the code of the .json file that I'm updating and what it comes out as. As I said in my other issue, I keep my things organized. I have a main page and when I go to payloads, it works fine
Payload code: (Spacing is there it's not showing up on Github for some reason. If you need me to I'll send my config.json. I'm still using some of the old format because it still works.)
{
	"entries": [
		{
			"name": "Page 1",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Default.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "SafeB9SInstaller",
			"url": "http://d0k3.secretalgorithm.com/SafeB9SInstaller/latest.zip",
			"inarchive": "SafeB9SInstaller.firm",
			"path": "/luma/payloads/Updater.firm"
		},
		{
			"name": "GodMode9 (latest commit)",
			"url": "https://d0k3.secretalgorithm.com/GodMode9TD/latest.zip",
			"inarchive": "GodMode9.firm",
			"path": "/luma/payloads/GodMode9.firm"
		},
		{
			"name": "GodMode9 (latest release)",
			"url": "https://github.com/d0k3/GodMode9",
			"inrelease": "GodMode9-*-*.zip",
			"inarchive": "GodMode9.firm",
			"path": "/luma/payloads/GodMode9.firm"
		},
		{
			"name": "Luma3DS (latest commit)",
			"url": "https://astronautlevel2.github.io/Luma3DS/latest.zip",
			"inarchive": "out/boot.firm",
			"path": "/Payloads/Luma.firm"
		},
		{
			"name": "Luma3DS (latest release)",
			"url": "https://github.com/AuroraWright/Luma3DS",
			"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/Payloads/Luma.firm"
		}
	]
}

But when I go back to the Main page the end of the code looks like:

		{
			"name": "payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		}
	]
}

But when I go from payloads to Default the end looks like:

		{
			"name": "payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		}
	]
}"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/Payloads/Luma.firm"
		}
	]
}

**Comment by LiquidFenrir** [comment]
I'm sorry but I really don't understand...use ` to open and close code blocks, that will keep the indentation.  
Please describe your problem in a better way

**Comment by killerfurze** [comment]
So this is the main page
`
{
	"entries": [
		{
			"name": "Update the file (will add more stuff)",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Default.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "Region Change",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Region Change.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "Decent Games",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Decent Games.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		}
	]
}
`
And this is the ending of the payloads file (thats causing the issue)
`
			"name": "GodMode9 (latest release)",
			"url": "https://github.com/d0k3/GodMode9",
			"inrelease": "GodMode9-*-*.zip",
			"inarchive": "GodMode9.firm",
			"path": "/luma/payloads/GodMode9.firm"
		},
		{
			"name": "Luma3DS (latest commit)",
			"url": "https://astronautlevel2.github.io/Luma3DS/latest.zip",
			"inarchive": "out/boot.firm",
			"path": "/Payloads/Luma.firm"
		},
		{
			"name": "Luma3DS (latest release)",
			"url": "https://github.com/AuroraWright/Luma3DS",
			"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/Payloads/Luma.firm"
		}
	]
}
`
After I go from the main page to the payloads, back to the main page the config breaks and the config.json at the end looks like
`
		{
			"name": "payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		}
	]
}"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/Payloads/Luma.firm"
		}
	]
}
`

**Comment by 46620** [comment]
The issue is when a page that has more items than a different page (different config.json files). If one has ore lines than the other, it replaces as much as the new one then keeps the rest of the old file where it was.
```{
	"entries": [
		{
			"name": "Update the file (will add more stuff)",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Default.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "Region Change (Breaks Config and is not done)",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Region Change.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "Decent Games",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inarchive": "Decent Games.json",
			"path": "/3ds/MultiUpdater/config.json"
		},
		{
			"name": "payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		}
	]
}
```
So I go from Default to Payloads
Payloads ending that is causing issue (has 6 items while Default has 4 items):
```
		{
			"name": "Luma3DS (latest commit)",
			"url": "https://astronautlevel2.github.io/Luma3DS/latest.zip",
			"inarchive": "out/boot.firm",
			"path": "/Payloads/Luma.firm"
		},
		{
			"name": "Luma3DS (latest release)",
			"url": "https://github.com/AuroraWright/Luma3DS",
			"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/Payloads/Luma.firm"
		}
	]
}
```

So when I go from Default to Payloads to Default, the ending of Default looks like
```
		{
			"name": "payloads",
			"url": "https://drive.google.com/uc?export=download&id=0BwV38SIw48pSUTMycm5DNVpkN3M",
			"inzip": "payloads.json",
			"path": "/3ds/MultiUpdater/config.json"
		}
	]
}"inrelease": "Luma3DSv*z",
			"inarchive": "boot.firm",
			"path": "/Payloads/Luma.firm"
		}
	]
}
```
Again, if you want me to attach the file to make it easier to explain I will

**Comment by LiquidFenrir** [comment]
no it's ok, it makes sense now

**Comment by JourneyOver** [comment]
Ahhh so this wasn't just happening to me a few days ago, I had this same exact problem and I was going to make a issue about it but I didn't know if it was only me or not at the time, kinda happy to see it's not only me with the problem. I ended up resorting to just making one big config file that is super unorganized to fix this for the time being :/ so hope an update can come along to fix this issue.

**Comment by JourneyOver** [comment]
@LiquidFenrir any word on when the fix for this will be released??? I see you closed this 16 days ago but there hasn't been an actual release for this fix yet :/

**Comment by andrewLarsson** [comment]
I had this issue with updating Luma3DS from v8.1 to v8.1.1. The new one is 1KB smaller than the old one. When I updated it, the last 1KB of the old one was still there in there `boot.firm` file. I was about to make an issue about it, but I noticed this one is the same problem. Any chance you could make a release for this?
