### ISSUE TITLE
More flexible Github support

### ISSUE THREAD

**Issue by replicaJunction** [LiquidFenrir/MultiUpdater#37]
I was looking into the idea of adding an entry in my config.json file to update MultiUpdater itself.

At present, I've got it working correctly with this entry:

```json
        {
            "name": "MultiUpdater (3DSX)",
            "url": "https://github.com/LiquidFenrir/MultiUpdater",
            "inrelease": "MultiUpdater-v*.*.*.zip",
            "inarchive": "3ds/MultiUpdater/MultiUpdater.3dsx",
            "path": "/3ds/MultiUpdater/MultiUpdater.3dsx"
        },
```

However, in looking through the MultiUpdater releases on Github, not every release has had a revision number. Right now the above code works, since the latest release is `MultiUpdater-v3.2.1.zip`, but if a 3.3 release comes out, the above "inrelease" line will fail for `MultiUpdater-v3.3.zip` since the third wildcard doesn't exist - it would be looking for something like `MultiUpdater-v3.3.0.zip`. Of course, with MultiUpdater specifically, you can just always use the same format for your releases, but that doesn't really address the root of the issue since other Github devs might not play by the rules.

Could the wildcard character * be extended to match one or more characters rather than just matching one character?

Thanks!

**Comment by LiquidFenrir** [comment]
you didnt read the release note for v3.0 :P  
And a better pattern matching system is already in the todo list
