### ISSUE TITLE
Feature?

### ISSUE THREAD

**Issue by GriffinG1** [LiquidFenrir/MultiUpdater#39]
Have MultiUpdater delete a CIA from the path after it's installed? Possibly as an option in the config..

**Comment by ValShaped** [comment]
~The problem with that is that MU can't yet create files, only overwrite existing ones.~

~Hopefully that, and this, gets implemented soon!~

EDIT: Didn't know MU could create files, whoops! Still, this is a good feature!

**Comment by LiquidFenrir** [comment]
good idea, and not sure where you got that @RubberBrony but it definitely can create files.

**Comment by GriffinG1** [comment]
Also maybe ability to update multiupdater through it, the same way fbi can update itself?

**Comment by ValShaped** [comment]
You can do that already, using a custom config. Having it in the example would be nice, but it's not too hard to put it in yourself.

**Comment by LiquidFenrir** [comment]
now added by the rewrite !
