### ISSUE TITLE
boot9strap download question

### ISSUE THREAD

**Issue by WolfHeroEX** [LiquidFenrir/MultiUpdater#40]
The four current versions of boot9strap 1.2 have names that don't seem to be compatible with the * filtering method since the version name differences happen right before the .zip and after the version number. Is there a proper way to put it into the config file, or do I just need to manually download it for now?

If there isn't a way, maybe a new filter to skip everything until it reaches the file extension would work?

**Comment by LiquidFenrir** [comment]
see #32, a better pattern matching system is planned.
