### ISSUE TITLE
Booting issues after Running MultiUpdater - Resolved

### ISSUE THREAD

**Issue by ceapy** [LiquidFenrir/MultiUpdater#43]
Hi, 
After changing to the new cfw and installing MultiUpdater, and then updating the CIA and cfw (through MultiUpdater) I am unable to start up my 3DS.
 
Whenever I press the power button the blue light flashes once for half a second and the screen stays black.

Was wondering if anyone else had this problem and was able to resolve the issue?

**Comment by ceapy** [comment]
Resolved issue by running the script 'setup_ctrnand_luma3ds' through godmode9.

**Comment by LiquidFenrir** [comment]
tip; mark things as resolved by clicking the "close issue" button. I'll close it with this comment but keep it in mind if you post more/on other projects.
And this will be fixed in the next release
