### ISSUE TITLE
[Suggestion] See the actual version before update it

### ISSUE THREAD

**Issue by BanCrash** [LiquidFenrir/MultiUpdater#44]
Hello! I like this program, and I think that could be very useful to know the version of the payload / cia you have installed and the version available, to know if you have to update it or not. I think I don't see this feature, however maybe I'm wrong, sorry if that the case.

About the actual version installed, if there isn't a way to read the actual version of all payloads / cias (I don't know if it is the case) I suggest to, at least, when you update it within multiupdater, the updater could write the version you download to a log file and shows that info the next time (for example: last update with MultiUpdater: 7.7. Available on server: 8.0).

Like I said, I don't know if this is even possible.

And thanks for the updater, is very useful!

**Comment by LiquidFenrir** [comment]
For MultiUpdater alone? easy.
For other applications? No. Best I can do is display the downloaded version, but not the one currently installed

**Comment by BanCrash** [comment]
Understood, thanks for the answer!
