### ISSUE TITLE
Application crashes on Old 3DS

### ISSUE THREAD

**Issue by TheMCNerd2017** [LiquidFenrir/MultiUpdater#45]
This is a self-explanatory issue, the app crashes when I attempt to launch it on my old 3DS. It happens after the Homebrew splash screen disappears. I installed the application through FBI's TitleDB option.

I have attached a picture of the crash bellow.

![img_1158](https://user-images.githubusercontent.com/25375242/29394435-3099de18-82d8-11e7-81fb-a8965139ff49.JPG)

**Comment by LiquidFenrir** [comment]
Already fixed, but no release :P
You were unlucky and managed to catch the (broken) release v3.3, this is one of the reasons I removed it and am fixing it now. Nice job I guess?

**Comment by TheMCNerd2017** [comment]
Odd how I got the v3.3 release, I guess it was because I downloaded the app from TitleDB in FBI.
