### ISSUE TITLE
MultiUpdater self-update installs cia instead of updating .3dsx

### ISSUE THREAD

**Issue by rctgamer3** [LiquidFenrir/MultiUpdater#47]
I'm running MultiUpdater through HBL - running the MultiUpdater option in MultiUpdater installs the cia version and does not update the .3dsx version. Maybe have MultiUpdater check if it's installed as a cia. If it's installed, install the new cia, if it isn't, update the .3dsx. Other easy option is to split the MultiUpdater option in the menu into the cia and .3dsx version.

**Comment by LiquidFenrir** [comment]
an automatic check seems a good idea, implemented!
