### ISSUE TITLE
[Bug] Delete archives in config doesn't actually delete them

### ISSUE THREAD

**Issue by sora10pls** [LiquidFenrir/MultiUpdater#49]
Tested with the latest release. The top of my config file reads the following:
```
"config": 
{
	"self_updater": true,
	"delete_archives": true,
	"delete_cias": true
},
```

Instead of deleting the `.archive` files after updating my payloads, the `.archive` files remain in the path `/3ds/MultiUpdater/`. Can't say the same for CIAs as I don't have any entries for CIAs in my config file, but I can do some testing in a bit for that if necessary.

**Comment by LiquidFenrir** [comment]
fixed in https://github.com/LiquidFenrir/MultiUpdater/commit/9335026f1382e985674d2965fb4b808d3217789e and the release!
