### ISSUE TITLE
Self-Update still deletes MultiUpdater after updating

### ISSUE THREAD

**Issue by greensad** [LiquidFenrir/MultiUpdater#51]
When Self-Update is enabled MultiUpdater is deleted despite the most recent release.

**Comment by Nomelas** [comment]
can't update the cia while it's running. it's possible though, as other apps do it all the time.

**Comment by greensad** [comment]
> "the self-updater works from the cia correctly now"

 I was referring to the notes in the latest release...

**Comment by LiquidFenrir** [comment]
that happens cause it deletes the installed title before installing the cia, if it is found. It will be removed for the next release, but keep in my mind it will now give an error if you try to install other titles while their latest version is already installed.
might break compatibility for the lazy ones who dont set the version in the cia
