### ISSUE TITLE
Feature Request - Downloading & extracting multiple files in single entry

### ISSUE THREAD

**Issue by Nomelas** [LiquidFenrir/MultiUpdater#52]
I posted this here as well:
https://gbatemp.net/threads/release-multiupdater-simple-updater-for-various-files-and-application.475662/

- I'd like to request a feature so that we can take multiple files from a single site/release/archive. Something like:

```
        {
            "name": "FBI.cia",
            "url": "https://github.com/Steveice10/FBI",
            "inrelease": "FBI.cia",
            "path": "/cias/FBI.cia",
            "inrelease": "FBI.3dsx",
            "path": "/3ds/FBI/FBI.3dsx"
        },
```
- And the ability to take multiple files from a single archive and put it in a directory. Something like:
```
        {
            "name": "Boot9strap.firm",
            "url": "https://github.com/SciresM/boot9strap",
            "inrelease": "boot9strap.*.zip",
            "inarchive": "boot9strap.firm",
            "inarchive": "boot9strap.firm.sha",
            "path": "/boot9strap/*"
        },
```
- Better yet, the ability to download from everything from just 1 click (rather than having multiple entries in the list). Like:
```
        {
            "name": "All-in-one Download" [
                {
                    "url": "https://github.com/SciresM/boot9strap",
                    "inrelease": "boot9strap.*-ntr.zip",
                    "inarchive": "boot9strap_ntr.firm",
                    "path": "/ntrboot/boot9strap_ntr.firm"
                },
                {
                    "url": "https://github.com/SciresM/boot9strap",
                    "inrelease": "boot9strap.*-ntr.zip",
                    "inarchive": "boot9strap_ntr.firm",
                    "path": "/ntrboot/boot9strap_ntr.firm"
                }
            ]
        },
        {
            "name": "Other options",
            "url": "https://github.com/blah/blahblah",
            "inrelease": "helloworld.cia",
            "path": "/cias/helloworld.cia"
        }
```
The reason I ask, is to both make it simpler to update some (So you're not re-downloading the same archive to get multiple files from it, or updating both the .3dsx or .cia with a single click) OR to provide an all-in-one click option for getting all the necessary homebrew when setting up a newly hacked 3ds.

**Comment by LiquidFenrir** [comment]
All in one can already be done with the marking shortcut L

**Comment by Nomelas** [comment]
I didnt know you could do this. is there any documentation on what fields are available as options in the json?
