### ISSUE TITLE
Can't download from notabug.org (freeshop)

### ISSUE THREAD

**Issue by Nomelas** [LiquidFenrir/MultiUpdater#53]
tried to get it to download from notabug but it doesnt work. example:
https://notabug.org/Paul_GameDev/freeShop/releases

**Comment by LiquidFenrir** [comment]
Notabug doesn't have an api to work with.
The release thing is limited to github 
Freeshop can update itself

**Comment by LiquidFenrir** [comment]
Notabug doesn't have an api to work with.
The release thing is limited to github 
Freeshop can update itself

**Comment by pbanj** [comment]
Paul is also not a dev. So he should change his name to Paul_ask_everyone_how_to_fix_everything
