### ISSUE TITLE
[question/possible feature] is it possible to download releases from gbatemp?

### ISSUE THREAD

**Issue by JourneyOver** [LiquidFenrir/MultiUpdater#54]
Pretty much the title, I've tried before but failed and idk if there is possibly some special trick to get it to work for gbatemp attachments..but if it's not possible then can this feature some how get added in? Would be nice for those pesky people who don't do their releases on github.

**Comment by greensad** [comment]
Yeah this would be pretty awesome if possible

**Comment by LiquidFenrir** [comment]
Short answer: no
Long answer: you'd have to change the url every time a new release comes, or make another site to do the conversion from post-to-attachment-url (shouldnt be too hard, a few regexs might do i, but this would be too special-purpose for MU in my opinion, just like notabug releases)
