### ISSUE TITLE
error code: c8a044dc if i try to update multiupdater

### ISSUE THREAD

**Issue by DragNeyht** [LiquidFenrir/MultiUpdater#56]
I tried to update MU via self-updater, but at the installation of the cia the installation failed.
I used my o3ds.
![2017-12-29_00-33-20 702_bot](https://user-images.githubusercontent.com/32341347/34425123-8e3936e4-ec29-11e7-8bd8-976e57d43050.jpg)

**Comment by DragNeyht** [comment]
sry, i found the answer for my question "that happens cause it deletes the installed title before installing the cia, if it is found. It will be removed for the next release, but keep in my mind it will now give an error if you try to install other titles while their latest version is already installed". you can close this issue.
But thanks for this nice project!

**Comment by LiquidFenrir** [comment]
Thank you for using it, and sorry for not answering, I am focusing on Anemone3DS for the time being, but MultiUpdater will eventually see work on it! Hopefully.
