### ISSUE TITLE
More Questions . . .

### ISSUE THREAD

**Issue by ghost** [LiquidFenrir/MultiUpdater#57]
If I set a file to download to a folder that doesn't exist, will it create it for me?

Also, what happens in cases like PKSM where the download folder has the same file name in two different folders. What does it grab? I am asking this because PKSM has a rosalina version and a hax version in its download folder

Also can thisgrab entire folders?

**Comment by LiquidFenrir** [comment]
1. Yes, it should create them. if it doesnt, that's a bug
2. it grabs the one you tell it to. give it the full path to the file in the zip
3. it cannot, only individual files

**Comment by ghost** [comment]
thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
