### ISSUE TITLE
7z extraction error

### ISSUE THREAD

**Issue by willis936** [LiquidFenrir/MultiUpdater#66]
7z extraction fails on some archives.  Universal updater recently addressed this with open_agb_firm.  I get an extraction error when using MultiUpdater on open_agb_firm.

https://github.com/profi200/open_agb_firm/issues/28

https://github.com/Universal-Team/Universal-Updater/releases/tag/v3.1.1

**Comment by LiquidFenrir** [comment]
Sorry, this project is not being worked on anymore, you won't see that being fixed by me.
