### ISSUE TITLE
Move Multiupdater directory to /3ds/data/

### ISSUE THREAD

**Issue by droped** [LiquidFenrir/MultiUpdater#7]

**Comment by Hikari-chan** [comment]
Bad idea, subdirectories in /3ds that don't contain a .3dsx or .smdh are shown in the HBL as navigable folders and tend to clutter up the list view. Additionally, MultiUpdater is available as a .3dsx, so /3ds/MultiUpdater is the perfect place for it; it avoids the aforementioned issue and keeps MultiUpdater's data from being splintered.
