### ISSUE TITLE
Seemingly random failures?

### ISSUE THREAD

**Issue by NinjaBoyLao** [LiquidFenrir/MultiUpdater#8]
The app just doesn't work sometimes for no apparent reason. I've painstakingly double and triple checked config.json, but each line is identically formatted. In my specific case, decrypt9WIP and EmuNAND9 and GodMode9 download correctly, but otphelper and hourglass9 and safemode9 all fail. d9 and emu9 are the first two entries, but godmode is the 5th, and the others are before and after it.

**Comment by LiquidFenrir** [comment]
That's a known problem that I'm trying to fix, for now the only known way around it is retrying  
EDIT: you're talking about the download fail right?

**Comment by NinjaBoyLao** [comment]
No i'm talking about it refusing to see config.json in my sd card at all even though it's clearly right there according to ftp, my actual card reader, and ctrxplorer

**Comment by Hikari-chan** [comment]
Not a reproducible issue. Have been using MultiUpdater for months, and though it has a laundry list of issues, this is likely due to a faulty or poor quality SD card.

**Comment by NinjaBoyLao** [comment]
Highly doubt it, its a sony card that i bought off the shelf at best buy

**Comment by LiquidFenrir** [comment]
Test your card with h2testw (make a backup first) or try the latest commit
