### ISSUE TITLE
Relative URLs in the location header field aren't handled (eg for http302)

### ISSUE THREAD

**Issue by YodaDaCoda** [LiquidFenrir/MultiUpdater#9]
If a 302 is encountered, there needs to be a check if the URL provided in the location header field is relative. Currently, relative URLs will fail.

**Comment by LiquidFenrir** [comment]
real late fix, but that should do it.
tell me if there are any bugs

**Comment by YodaDaCoda** [comment]
Could you compile a release so TitleDB updates please?

**Comment by LiquidFenrir** [comment]
There you go!
Not sure if titledb updates are automatic but I made a new release

**Comment by YodaDaCoda** [comment]
Thanks! TitleDB does update automatically based on github releases. Works great!
